Repository kubernetes-client/go-base, pull requests merged in 2018-08, with the labels that each got.

#4 Add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/S

#6 added OWNERS file.
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS

#7 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: cncf-cla: yes, lgtm, size/S

#8 Remove link to kubernetes-client/community
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
